baseURL: 'https://monokemonoke.github.io/portfolio/'
publishDir: docs
languageCode: ' ja-jp'
title: monokemonoke
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

params:
  assets:
    favicon: profile.jpg
    
  profileMode:
      enabled: True
      title: monokemonoke
      imageUrl: profile.jpg
      imageWidth: 200
      imageHeight: 200
      imageTitle: monokemonoke's image

  socialIcons:
    - name: github
      url: https://github.com/monokemonoke
    - name: twitter
      url: https://twitter.com/monokemonoke
