baseURL: 'https://monokemonoke.github.io/profile/'
publishDir: Docs
languageCode: ' ja-jp'
title: monokemonoke
theme: PaperMod

params:
  profileMode:
      enabled: True
      title: monokemonoke
      imageUrl: profile.jpg
      imageWidth: 200
      imageHeight: 200
      imageTitle: monokemonoke's image
